import { AuditNote, AuditReportMeta } from '../core/types';

function statusEmoji(s: AuditNote['status']): string {
  return s === 'fixed' ? '✅' : '🔴';
}

function statusLabel(s: AuditNote['status']): string {
  return s === 'fixed' ? 'Düzeltildi' : 'Açık';
}

export function buildMarkdown(notes: AuditNote[], meta: AuditReportMeta): string {
  const open = notes.filter((n) => n.status === 'open').length;
  const fixed = notes.filter((n) => n.status === 'fixed').length;

  let md = `# 🛡️ Nokta Dashboard: Autonomous Audit Report\n\n`;
  md += `> [!NOTE]\n`;
  md += `> This report was automatically generated by the Forge Maintenance Pipeline.\n\n`;
  
  md += `**Project:** ${meta.appName}  \n`;
  md += `**Exported At:** ${new Date(meta.exportedAt).toLocaleString('tr-TR')}  \n`;
  md += `**Summary:** Total ${meta.totalNotes} audits (🟢 ${fixed} fixed, 🔴 ${open} pending)\n\n`;
  md += `--- \n\n`;

  const grouped: Record<string, AuditNote[]> = {};
  notes.forEach((n) => {
    (grouped[n.screenName] = grouped[n.screenName] || []).push(n);
  });

  for (const [screen, items] of Object.entries(grouped)) {
    md += `## 🖥️ Screen: ${screen}\n\n`;
    
    for (const n of items) {
      const statusBadge = n.status === 'fixed' ? '✅ FIXED' : '🔴 PENDING';
      md += `### [${statusBadge}] ${n.note.split('\n')[0]}\n\n`;
      
      if (n.screenshot) {
        md += `#### 📸 Evidence\n`;
        md += `![Screenshot](${n.screenshot})\n\n`;
      }

      md += `#### 📝 Audit Details\n`;
      md += `| Attribute | Value |\n`;
      md += `| :--- | :--- |\n`;
      md += `| **Status** | ${n.status.toUpperCase()} |\n`;
      md += `| **Timestamp** | ${new Date(n.timestamp).toLocaleString('tr-TR')} |\n`;
      if (n.reporterId) md += `| **Reporter** | ${n.reporterId} |\n`;
      md += `\n> **Prompt:** ${n.note}\n\n`;
      
      md += `---\n\n`;
    }
  }

  md += `\n*Generated by Antigravity AI Forge Engine*\n`;
  return md;
}

